const teamInfo = {
    "2676a": {team_abbreviation: "AUA", initial_rating: 749.3}, //Austin Anarchy (A)
    "2685a": {team_abbreviation: "CWB", initial_rating: 781.7}, //Carolina Wreckingballs (A)
    "2686a": {team_abbreviation: "CBRD", initial_rating: 722.2}, //Casco Bay Roller Derby (A)
    "2686b": {team_abbreviation: "CBRD(B)", initial_rating: 360}, //Casco Bay Roller Derby (B)
    "2687a": {team_abbreviation: "CBB", initial_rating: 817.3}, //Chicago Bruise Brothers (A)
    "2687b": {team_abbreviation: "CBB(B)", initial_rating: 400}, //Chicago Bruise Brothers (B)
    "2689a": {team_abbreviation: "CGRD", initial_rating: 573.4}, //Cleveland Guardians Roller Derby (A)
    "2692a": {team_abbreviation: "CTB", initial_rating: 636}, //Crash Test Brummies (A)
    "2693a": {team_abbreviation: "DGC", initial_rating: 902.5}, //Denver Ground Control (A)
    "2694a": {team_abbreviation: "DMRD", initial_rating: 600.6}, //Detroit Mens Roller Derby (A)
    "2696a": {team_abbreviation: "ChCRD", initial_rating: 719.1}, //Chinook City Roller Derby (A)
    "2699a": {team_abbreviation: "CRD", initial_rating: 750.6, distance_clause_applies: true}, //Concussion Roller Derby (A)
    "2699b": {team_abbreviation: "CRD(B)", initial_rating: 375, distance_clause_applies: true}, //Concussion Roller Derby (B)
    "2701a": {team_abbreviation: "MCM", initial_rating: 973.6}, //Magic City Misfits (A)
    "2702a": {team_abbreviation: "MRD", initial_rating: 861}, //Manchester Roller Derby (A)
    "2702b": {team_abbreviation: "MRD(B)", initial_rating: 600}, //Manchester Roller Derby (B)
    "2714a": {team_abbreviation: "PAN", initial_rating: 619.4}, //Panam Squad (A)
    "2715a": {team_abbreviation: "PHH", initial_rating: 766.7}, //Philadelphia Hooligans (A)
    "2715b": {team_abbreviation: "PHH(B)", initial_rating: 375}, //Philadelphia Hooligans (B)
    "2717a": {team_abbreviation: "PSOD", initial_rating: 792.4, distance_clause_applies: true}, //Puget Sound Outcast Derby (A)
    "2719a": {team_abbreviation: "RCR", initial_rating: 794.1}, //Race City Rebels (A)
    "2723a": {team_abbreviation: "SDA", initial_rating: 809.8, distance_clause_applies: true}, //San Diego Aftershocks (A)
    "2723b": {team_abbreviation: "SDA(B)", initial_rating: 400, distance_clause_applies: true}, //San Diego Aftershocks (B)
    "2725a": {team_abbreviation: "SWS", initial_rating: 647.6}, //South Wales Silures (A)
    "2727a": {team_abbreviation: "SLGK", initial_rating: 962.4}, //Saint Louis Gatekeepers (A)
    "2727b": {team_abbreviation: "SLGK(B)", initial_rating: 650}, //Saint Louis Gatekeepers (B)
    "2733a": {team_abbreviation: "TIL", initial_rating: 758.6}, //The Inhuman League (A)
    "2735a": {team_abbreviation: "TMRD", initial_rating: 762.7}, //Toronto Mens Roller Derby (A)
    "2737a": {team_abbreviation: "TNF", initial_rating: 806}, //Tyne and Fear Roller Derby (A)
    "2737b": {team_abbreviation: "TNF(B)", initial_rating: 550}, //Tyne and Fear Roller Derby (B)
    "3013a": {team_abbreviation: "TRD", initial_rating: 610}, //Terminus Roller Derby (A)
    "13122a": {team_abbreviation: "KMRD", initial_rating: 689}, //Kent Mens Roller Derby (A)
    "17403a": {team_abbreviation: "PIT", initial_rating: 787.3}, //Pittsburgh Roller Derby (A)
    "17403b": {team_abbreviation: "PIT(B)", initial_rating: 480}, //Pittsburgh Roller Derby (B)
    "17404a": {team_abbreviation: "DHR", initial_rating: 515.5}, //D.H.R. Men's Roller Derby (A)
    "17405a": {team_abbreviation: "FCF", initial_rating: 663.4}, //Flour City Roller Derby (A)
    "17908a": {team_abbreviation: "DIS", initial_rating: 792, distance_clause_applies: true}, //Disorder (A)
    "17909a": {team_abbreviation: "BBRD", initial_rating: 743}, //Borderland Bandits Roller Derby (A)
    "17910a": {team_abbreviation: "NDT", initial_rating: 600}, //Nordicks de Touraine (A)
    "17911a": {team_abbreviation: "RDT", initial_rating: 825}, //Roller Derby Toulouse (A)
    "17912a": {team_abbreviation: "TMP", initial_rating: 650}, //Tampa Roller Derby (A)
    "17913a": {team_abbreviation: "SDRD", initial_rating: 879}, //Southern Discomfort Roller Derby (A)
    "17914a": {team_abbreviation: "DDD", initial_rating: 760}, //Dallas Derby Devils (A)
    "17915a": {team_abbreviation: "RDNA", initial_rating: 575}, //Roller Derby Nantes Atlantique (A)
    "17916a": {team_abbreviation: "ORD", initial_rating: 670}, //Orcet Roller Derby (A)
    "17917a": {team_abbreviation: "WRD", initial_rating: 725}, //Wirral Roller Derby (A)
}